=== cairis-platform/cairis/cairis-gh-pages/dtd/locations.dtd
<!-- 
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

<!-- DTD for CAIRIS location models -->

<!ELEMENT locations (location*)>
<!ATTLIST locations name CDATA #REQUIRED>
<!ATTLIST locations diagram CDATA #REQUIRED>

<!ELEMENT location (asset_instance*,persona_instance*,link+)>
<!ATTLIST location name CDATA #REQUIRED>

<!ELEMENT asset_instance EMPTY>
<!ATTLIST asset_instance name CDATA #REQUIRED>
<!ATTLIST asset_instance asset CDATA #REQUIRED>

<!ELEMENT persona_instance EMPTY>
<!ATTLIST persona_instance name CDATA #REQUIRED>
<!ATTLIST persona_instance persona CDATA #REQUIRED>

<!ELEMENT link EMPTY>
<!ATTLIST link name CDATA #REQUIRED>

=== cairis-platform/cairis/examples/exemplars/ACME_Water/PooleWWTW.xml
<?xml version="1.0"?>
<!DOCTYPE locations PUBLIC "-//CAIRIS//DTD LOCATIONS  1.0//EN" "https://cairis.org/dtd/locations.dtd">

<locations name="PooleWWTW" diagram="None">
  <location name="PC1">
    <link name="WCH_1" />
    <link name="WCH_2" />
    <link name="WCH_3" />
    <link name="WCH_4" />
  </location>
  <location name="WCH_1">
    <asset_instance name="PC-9" asset="ICT PC" />
    <link name="PC1" />
  </location>
  <location name="WCH_2">
    <asset_instance name="PC-67" asset="ICT PC" />
    <link name="PC1" />
  </location>
  <location name="WCH_3">
    <asset_instance name="PC-76" asset="ICT PC" />
    <link name="PC1" />
  </location>
  <location name="WCH_4">
    <asset_instance name="SWS-1" asset="SCADA Workstation" />
    <asset_instance name="PC-23" asset="ICT PC" />
    <asset_instance name="PC-24" asset="ICT PC" />
    <asset_instance name="PC-25" asset="ICT PC" />
    <persona_instance name="Rick" persona="Rick" />
    <link name="PC1" />
    <link name="PC2" />
    <link name="WCH_5" />
  </location>
  <location name="WCH_5">
    <link name="WCH_4" />
    <link name="WCH_6" />
  </location>
  <location name="WCH_6">
    <asset_instance name="M12" asset="Modem" />
    <asset_instance name="R18" asset="Router" />
    <asset_instance name="PC-11" asset="ICT PC" />
    <persona_instance name="Barry" persona="Barry" />
    <link name="WCH_5" />
  </location>
  <location name="PC2">
    <link name="WCH_4" />
    <link name="MR_1" />
    <link name="MR_2" />
    <link name="MR_3" />
    <link name="MR_4" />
  </location>
  <location name="MR_1">
    <link name="PC2" />
  </location>
  <location name="MR_2">
    <link name="PC2" />
  </location>
  <location name="MR_3">
    <link name="PC2" />
  </location>
  <location name="MR_4">
    <link name="PC2" />
  </location>
</locations>
