=== cairis-platform/cairis/cairis/config/architectural_pattern.dtd
<!-- 
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->


<!-- DTD for template CAIRIS architectural patterns -->

<!ELEMENT architectural_pattern (synopsis,access_right*,protocol*,privilege*,surface_type*,role*,asset*,requirement*,goal*,component*,connector*)>
<!ATTLIST architectural_pattern name CDATA #REQUIRED>
<!ELEMENT synopsis (#PCDATA)>

<!ELEMENT access_right (description,rationale)>
<!ATTLIST access_right name CDATA #REQUIRED>
<!ATTLIST access_right value CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>

<!ELEMENT protocol (description,rationale)>
<!ATTLIST protocol name CDATA #REQUIRED>
<!ATTLIST protocol value CDATA #REQUIRED>

<!ELEMENT privilege (description,rationale)>
<!ATTLIST privilege name CDATA #REQUIRED>
<!ATTLIST privilege value CDATA #REQUIRED>

<!ELEMENT surface_type (description,rationale)>
<!ATTLIST surface_type name CDATA #REQUIRED>
<!ATTLIST surface_type value CDATA #REQUIRED>

<!ELEMENT role (description)>
<!ATTLIST role name CDATA #REQUIRED>
<!ATTLIST role type (Stakeholder | Attacker) #REQUIRED>
<!ATTLIST role short_code CDATA #REQUIRED>

<!ELEMENT asset (description,tag*,significance,interface*,security_property*)>
<!ATTLIST asset name CDATA #REQUIRED>
<!ATTLIST asset short_code CDATA #REQUIRED>
<!ATTLIST asset type (Information | Systems | Software | Hardware | People) #REQUIRED>
<!ATTLIST asset surface_type CDATA #REQUIRED>
<!ATTLIST asset access_right CDATA #REQUIRED>

<!ELEMENT security_property (rationale)>
<!ATTLIST security_property property (confidentiality | integrity | availability | accountability | anonymity | pseudonymity | unlinkability | unobservability) #REQUIRED>
<!ATTLIST security_property value (None | Low | Medium | High) #REQUIRED>


<!ELEMENT tag EMPTY>
<!ATTLIST tag name CDATA #REQUIRED>

<!ELEMENT significance (#PCDATA)>

<!ELEMENT interface EMPTY>
<!ATTLIST interface name CDATA #REQUIRED>
<!ATTLIST interface type (provided | required) #REQUIRED> 
<!ATTLIST interface access_right CDATA #REQUIRED>
<!ATTLIST interface privilege CDATA #REQUIRED>

<!ELEMENT requirement (description,rationale,fit_criterion)>
<!ATTLIST requirement asset CDATA #REQUIRED>
<!ATTLIST requirement name CDATA #REQUIRED>
<!ATTLIST requirement type (Functional | Data | Look_and_Feel | Usability | Performance | Operational | Maintainability | Portability | Security | Cultural_and_Political | Legal) #REQUIRED>
<!ELEMENT rationale (#PCDATA)>
<!ELEMENT fit_criterion (#PCDATA)>

<!ELEMENT goal (definition,rationale,concern*,responsibility*)>
<!ATTLIST goal name CDATA #REQUIRED>
<!ELEMENT definition (#PCDATA)>
<!ELEMENT concern EMPTY>
<!ATTLIST concern name CDATA #REQUIRED>
<!ELEMENT responsibility EMPTY>
<!ATTLIST responsibility name CDATA #REQUIRED>

<!ELEMENT component (description,interface*,structure*,component_requirement*,component_goal*,component_goal_association*)>
<!ATTLIST component name CDATA #REQUIRED>

<!ELEMENT structure EMPTY>
<!ATTLIST structure head_asset CDATA #REQUIRED>
<!ATTLIST structure head_adornment (Association | Aggregation | Composition | Inheritance) #REQUIRED>
<!ATTLIST structure head_nav (1 | 0) #REQUIRED>
<!ATTLIST structure head_nry (1 | a | 1..a) #REQUIRED>
<!ATTLIST structure head_role CDATA #REQUIRED>
<!ATTLIST structure tail_role CDATA #REQUIRED>
<!ATTLIST structure tail_nry (1 | a | 1..a) #REQUIRED>
<!ATTLIST structure tail_nav (1 | 0) #REQUIRED>
<!ATTLIST structure tail_adornment (Association | Aggregation | Composition | Inheritance) #REQUIRED>
<!ATTLIST structure tail_asset CDATA #REQUIRED>
<!ELEMENT component_requirement EMPTY>
<!ATTLIST component_requirement name CDATA #REQUIRED>
<!ELEMENT component_goal EMPTY>
<!ATTLIST component_goal name CDATA #REQUIRED>

<!ELEMENT component_goal_association (rationale)>
<!ATTLIST component_goal_association goal_name CDATA #REQUIRED>
<!ATTLIST component_goal_association ref_type (and | or) #REQUIRED>
<!ATTLIST component_goal_association subgoal_name CDATA #REQUIRED>


<!ELEMENT connector EMPTY>
<!ATTLIST connector name CDATA #REQUIRED>
<!ATTLIST connector protocol CDATA #REQUIRED>
<!ATTLIST connector from_component CDATA #REQUIRED>
<!ATTLIST connector from_role CDATA #REQUIRED>
<!ATTLIST connector from_interface CDATA #REQUIRED>
<!ATTLIST connector to_component CDATA #REQUIRED>
<!ATTLIST connector to_interface CDATA #REQUIRED>
<!ATTLIST connector to_role CDATA #REQUIRED>
<!ATTLIST connector access_right CDATA #REQUIRED>
<!ATTLIST connector asset_name CDATA #REQUIRED>

=== cairis-platform/cairis/examples/architecture/PolicyArchitecture.xml
<?xml version="1.0"?>
<!DOCTYPE architectural_pattern PUBLIC "-//CAIRIS//DTD COMPONENT 1.0//EN" "https://cairis.org/dtd/architectural_pattern.dtd">

<!-- 
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->


<architectural_pattern name="Policy architecture">
<synopsis>Model illustrating policy architecture</synopsis>

<access_right name="trusted" value="10">
  <description>None</description>
  <rationale>None</rationale>
</access_right>
<access_right name="authenticated" value="5">
  <description>None</description>
  <rationale>None</rationale>
</access_right>
<access_right name="anonymous" value="1">
  <description>None</description>
  <rationale>None</rationale>
</access_right>

<protocol name="JSON-RPC" value="10">
  <description>None</description>
  <rationale>None</rationale>
</protocol>
<protocol name="TLS" value="1">
  <description>None</description>
  <rationale>None</rationale>
</protocol>

<privilege name="privileged" value="10">
  <description>None</description>
  <rationale>None</rationale>
</privilege>
<privilege name="normal" value="1">
  <description>None</description>
  <rationale>None</rationale>
</privilege>

<surface_type name="JSON" value="10">
  <description>None</description>
  <rationale>None</rationale>
</surface_type>
<surface_type name="Unconstrained XML" value="5">
  <description>None</description>
  <rationale>None</rationale>
</surface_type>
<surface_type name="Constrained XML" value="1">
  <description>None</description>
  <rationale>None</rationale>
</surface_type>
<surface_type name="Client application" value="10">
  <description>None</description>
  <rationale>None</rationale>
</surface_type>
<surface_type name="Privileged application" value="1">
  <description>None</description>
  <rationale>None</rationale>
</surface_type>


<asset name="Policy File" short_code="POL" type="Information" surface_type="Unconstrained XML" access_right="trusted">
  <description>XACML Policy File</description>
  <tag name="Policy" />
  <significance>Defines the basis of policy decisions.</significance>
</asset>
<asset name="Access Request" short_code="AC_REQ" type="Information" surface_type="JSON" access_right="authenticated">
  <description>Request for a resources</description>
  <tag name="Access Request" />
  <significance>Request for a resources</significance>
</asset>
<asset name="Access Requestor" short_code="AC_RE" type="Software" surface_type="Client application" access_right="authenticated">
  <description>Requests access to resources</description>
  <tag name="Access Requestor" />
  <significance>Requests access to resources</significance>
</asset>
<asset name="Decision Wrapper" short_code="DE_WR" type="Software" surface_type="Privileged application" access_right="trusted">
  <description>Manages the dialogue between clients and the policy manager</description>
  <significance>Response for the dialogue between clients and the policy manager</significance>
</asset>
<asset name="Access Manager" short_code="AC_MA" type="Software" surface_type="Privileged application" access_right="trusted">
  <description>Makes policy decisions</description>
  <significance>Makes the final decision by combining XACML access control with DHDF data</significance>
</asset>
<asset name="Data Reader" short_code="DA_RE" type="Software" surface_type="Privileged application" access_right="trusted">
  <description>Data Reader</description>
  <significance>Responsible for abstracting the communication between the DHDF Engine and the Request Context</significance>
</asset>
<asset name="Request Context" short_code="RE_CO" type="Information" surface_type="Unconstrained XML" access_right="trusted">
  <description>Encapsulates the data and credentials released by a user in a given session.</description>
  <tag name="Request Context" />
  <significance>Responsible for converting the request data into the canonical form required for evaluation</significance>
</asset>
<asset name="DHDF Engine" short_code="DHDF_ENG" type="Software" surface_type="Privileged application" access_right="trusted">
  <description>Provides privacy and data handling functionality</description>
  <significance>Responsible for managing and evaluating relevant data handling (privacy) policies</significance>
</asset>
<asset name="PDP Cache" short_code="PDPC" type="Software" surface_type="Privileged application" access_right="trusted">
  <description>PDP Cache</description>
  <significance>Stores PDP decisions that could be shared among personal devices.</significance>
</asset>
<asset name="JSON-RPC Object" short_code="JSON-RPC_OBJT" type="Information" surface_type="JSON" access_right="authenticated">
  <description>JSON-RPC Object</description>
  <significance>Encapsulates data sent between API clients and API implementations</significance>
</asset>
<asset name="JSON Object" short_code="JSON_OBJT" type="Information" surface_type="JSON" access_right="authenticated">
  <description>JSON Object</description>
  <significance>Encapsulates data sent between components within the same node process</significance>
</asset>
<requirement name="API control" asset="Access Requestor" type="Functional">
  <description>Users and other stakeholders shall be able to control access by web applications to JavaScript APIs.  These APIs may allow access to local and remote resources.</description>
  <rationale>None</rationale>
  <fit_criterion>None</fit_criterion>
</requirement>
<requirement name="Device policy" asset="Access Requestor" type="Functional">
  <description>Users shall be able to create both device-specific and device-agnostic policies.</description>
  <rationale>None</rationale>
  <fit_criterion>None</fit_criterion>
</requirement>
<requirement name="Policy synchronisation" asset="PDP Cache" type="Functional">
  <description>The platform shall provide synchronisation for access control policies, so that policies can be desceibed on one platform and enforced on all.</description>
  <rationale>None</rationale>
  <fit_criterion>None</fit_criterion>
</requirement>
<requirement name="Context-sensitive access control" asset="Request Context" type="Functional">
  <description>The platform shall allow context-sensitive access control decisions: e.g. these may change depending on the environment.</description>
  <rationale>None</rationale>
  <fit_criterion>None</fit_criterion>
</requirement>
<requirement name="Qualified data use" asset="Request Context" type="Functional">
  <description>The platform shall protect user privacy: access requestors shall be able to qualify how they will use the data they are requesting, and users shall be able to express constraints about data disclosure.</description>
  <rationale>None</rationale>
  <fit_criterion>None</fit_criterion>
</requirement>


<component name="Policy Manager">
  <description>XACML based policy manager component.</description>
  <interface name="enforceRequest" type="provided" access_right="trusted" privilege="normal" />
  <structure head_asset="Decision Wrapper" head_adornment="Association" head_nav="0" head_nry="1" head_role="" tail_role="" tail_nry="1..a" tail_nav="1" tail_adornment="Association" tail_asset="Access Request" />
  <structure head_asset="Decision Wrapper" head_adornment="Association" head_nav="0" head_nry="1" head_role="" tail_role="" tail_nry="1" tail_nav="1" tail_adornment="Association" tail_asset="Access Manager" />
  <structure head_asset="Access Manager" head_adornment="Composition" head_nav="0" head_nry="1" head_role="" tail_role="" tail_nry="1" tail_nav="1" tail_adornment="Association" tail_asset="DHDF Engine" />
  <structure head_asset="DHDF Engine" head_adornment="Association" head_nav="0" head_nry="1" head_role="" tail_role="" tail_nry="1" tail_nav="1" tail_adornment="Association" tail_asset="Data Reader" />
  <structure head_asset="Data Reader" head_adornment="Association" head_nav="0" head_nry="a" head_role="" tail_role="" tail_nry="a" tail_nav="1" tail_adornment="Association" tail_asset="Request Context" />
  <structure head_asset="Access Manager" head_adornment="Association" head_nav="0" head_nry="1" head_role="" tail_role="" tail_nry="1" tail_nav="1" tail_adornment="Association" tail_asset="PDP Cache" />
  <structure head_asset="PDP Cache" head_adornment="Aggregation" head_nav="1" head_nry="a" head_role="" tail_role="loads" tail_nry="1..a" tail_nav="0" tail_adornment="Association" tail_asset="Policy File" />
  <component_requirement name="Policy synchronisation" />
  <component_requirement name="API control" />
  <component_requirement name="Device policy" />
  <component_requirement name="Context-sensitive access control" />
  <component_requirement name="Qualified data use" />
</component>

<component name="Discovery Module">
  <description>Discovery API implementation</description>
  <interface name="enforceRequest" type="required" access_right="trusted" privilege="normal" />
  <interface name="authenticate" type="provided" access_right="trusted" privilege="normal" />
  <structure head_asset="Access Request" head_adornment="Association" head_nav="0" head_nry="1" head_role="" tail_role="" tail_nry="1" tail_nav="1" tail_adornment="Association" tail_asset="JSON Object" />
</component>

<component name="Discovery Client">
