=== cairis-platform/cairis/cairis/config/attack_pattern.dtd
<!-- 
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

<!-- DTD for CAIRIS attack patterns -->

<!ELEMENT attack_pattern (obstacle*,intent,motivation+,applicability,structure,participant+,collaboration,consequences,implementation,known_uses?,related_patterns?)>

<!ATTLIST attack_pattern name CDATA #REQUIRED>
<!ATTLIST attack_pattern likelihood (Incredible | Improbable | Remote | Occasional | Probable | Frequent) #REQUIRED>
<!ATTLIST attack_pattern severity (Negligible | Marginal | Critical | Catastrophic) #REQUIRED>

<!ELEMENT obstacle (definition,concern*,responsibility*,probability?)>
<!ATTLIST obstacle name CDATA #REQUIRED>
<!ATTLIST obstacle category (Confidentiality_Threat | Integrity_Threat | Availability_Threat | Accountability_Threat | Vulnerability | Duration | Frequency | Demands | Goal_Support | Anonymity_Threat | Pseudonymity_Threat | Unlinkability_Threat | Unobservability_Threat | Threat ) #REQUIRED>
<!ELEMENT definition (#PCDATA)>
<!ELEMENT concern EMPTY>
<!ATTLIST concern name CDATA #REQUIRED>
<!ELEMENT responsibility EMPTY>
<!ATTLIST responsibility name CDATA #REQUIRED>
<!ELEMENT probability (rationale)>
<!ATTLIST probability value CDATA #REQUIRED>
<!ELEMENT rationale (#PCDATA)>


<!ELEMENT intent (#PCDATA)>

<!ELEMENT motivation (description)>
<!ATTLIST motivation goal (confidentiality | integrity | availability | accountability | anonymity | pseudonymity | unlinkability | unobservability) #REQUIRED>
<!ATTLIST motivation value (None | Low | Medium | High) #REQUIRED>
<!ELEMENT description (#PCDATA)>

<!ELEMENT applicability EMPTY>
<!ATTLIST applicability environment CDATA #REQUIRED>

<!ELEMENT structure EMPTY>
<!ATTLIST structure attack CDATA #REQUIRED>
<!ATTLIST structure exploit CDATA #REQUIRED>
<!ATTLIST structure attack_obstacle CDATA #IMPLIED>
<!ATTLIST structure exploit_obstacle CDATA #IMPLIED>

<!ELEMENT participant (motive+,capability+)>
<!ATTLIST participant name CDATA #REQUIRED>
<!ELEMENT motive EMPTY>
<!ATTLIST motive name CDATA #REQUIRED>
<!ELEMENT capability EMPTY>
<!ATTLIST capability name CDATA #REQUIRED>
<!ATTLIST capability value (Low | Medium | High) #REQUIRED>

<!ELEMENT collaboration (target+,exploit+)>
<!ELEMENT target EMPTY>
<!ATTLIST target name CDATA #REQUIRED>
<!ELEMENT exploit EMPTY>
<!ATTLIST exploit name CDATA #REQUIRED>

<!ELEMENT consequences (#PCDATA)>
<!ELEMENT implementation (description,obstacle_association*)>

<!ELEMENT obstacle_association (rationale)>
<!ATTLIST obstacle_association obstacle_name CDATA #REQUIRED>
<!ATTLIST obstacle_association ref_type (and | or) #REQUIRED>
<!ATTLIST obstacle_association subobstacle_name CDATA #REQUIRED>

<!ELEMENT known_uses (#PCDATA)>
<!ELEMENT related_patterns (#PCDATA)>

=== cairis-platform/cairis/examples/architecture/XACMLAttackPattern.xml
<?xml version="1.0"?>
<!DOCTYPE attack_pattern PUBLIC "-//CAIRIS//DTD ATTACKPATTERN 1.0//EN" "https://cairis.org/dtd/attack_pattern.dtd">

<!-- 
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->


<attack_pattern name="Request footprinting" likelihood="Occasional" severity="Critical"> 
  <intent>Glean an understanding of what resources are available on a device by eavesdropping on requests.</intent> 
  <motivation goal="confidentiality" value="Low"> 
    <description>Ethan wants to get a better understanding of what resources are under policy control.</description>
  </motivation>
  <applicability environment="Complete" />
  <structure attack="Network Eavesdropping" exploit="Missing XML Validation" /> 
  <participant name="Ethan">
    <motive name="System resource theft" />
    <responsibility name="Technology" value="Medium" />
    <responsibility name="Software" value="Medium" />
    <responsibility name="Knowledge/Methods" value="Medium" />
  </participant>
  <collaboration>
    <target name="Access Requestor" /> 
    <exploit name="Access Request" />
  </collaboration>
  <consequences>Impact of attack</consequences>
  <implementation>This scenario describes how Ethan carries out request footprinting</implementation>
  <known_uses>None</known_uses>
  <related_patterns>None</related_patterns>
</attack_pattern>

=== cairis-platform/cairis/cairis/test/XACMLAttackPattern.xml
<?xml version="1.0"?>
<!DOCTYPE attack_pattern PUBLIC "-//CAIRIS//DTD ATTACKPATTERN 1.0//EN" "https://cairis.org/dtd/attack_pattern.dtd">

<!-- 
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->


<attack_pattern name="Request footprinting" likelihood="Occasional" severity="Critical"> 

  <obstacle name="Eavesdrop access requests" category="Confidentiality_Threat" >
    <definition>Eavesdrop access requests</definition>
  </obstacle>
  <obstacle name="Eavesdrop request enforcement channel" category="Confidentiality_Threat" >
    <definition>Eavesdrop access request enforcement channel.</definition>
  </obstacle>
  <obstacle name="Eavesdrop Context Manager" category="Confidentiality_Threat" >
    <definition>Eavesdrop use of policy management in context manager</definition>
  </obstacle>
  <obstacle name="Eavesdrop Policy Manager" category="Confidentiality_Threat" >
    <definition>Eavesdrop software making use of the Policy Manager</definition>
    <concern name="Access Requestor" />
  </obstacle>
  <obstacle name="Eavesdrop RPC Call Log" category="Confidentiality_Threat" >
    <definition>Eavesdrop logged use of policy management in RPC call log</definition>
    <concern name="RPC Call Log" />
  </obstacle>
  <obstacle name="Eavesdrop Context Database" category="Confidentiality_Threat" >
    <definition>Eavesdrop use of policy management in Context Database</definition>
    <concern name="Context DB Instance" />
  </obstacle>

  <obstacle name="Missing XML document validation" category="Vulnerability" >
    <definition>XML document does not contain a validating DTD or schema</definition>
  </obstacle>
  <obstacle name="Missing Access Request validation" category="Vulnerability" >
    <definition>XML representation of access request contains no validating DTD or schema.</definition>
    <concern name="Access Request" />
    <responsibility name="Developer of webinos Platform" />
  </obstacle>
  <obstacle name="Missing Policy file validation" category="Vulnerability" >
    <definition>Policy file contains no validating DTD or schema</definition>
    <concern name="Policy File" />
    <responsibility name="Developer of webinos Platform" />
  </obstacle>

  <intent>Glean an understanding of what resources are available on a device by eavesdropping on requests.</intent> 
  <motivation goal="confidentiality" value="Low"> 
    <description>Ethan wants to get a better understanding of what resources are under policy control.</description>
  </motivation>
  <applicability environment="Complete" />
  <structure attack="Network Eavesdropping" attack_obstacle="Eavesdrop request enforcement channel" exploit="Missing XML Validation" exploit_obstacle="Missing XML document validation" /> 
  <participant name="Ethan">
    <motive name="System resource theft" />
    <capability name="Technology" value="Medium" />
    <capability name="Software" value="Medium" />
    <capability name="Knowledge/Methods" value="Medium" />
  </participant>
  <collaboration>
    <target name="Application Data" /> 
    <exploit name="Application Data" />
  </collaboration>
  <consequences>Impact of attack</consequences>
  <implementation>
    <description>Ethan eavesdrop on traffic to and from the policy manager to find possible policy management vulnerabilities.</description>

    <obstacle_association obstacle_name="Missing XML document validation" ref_type="or" subobstacle_name="Missing Access Request validation">
      <rationale>No evidence of validation in the current policy manager implementation.</rationale>
    </obstacle_association>
    <obstacle_association obstacle_name="Missing XML document validation" ref_type="or" subobstacle_name="Missing policy file validation">
      <rationale>No evidence of validation in the current policy manager implementation.</rationale>
    </obstacle_association>
    <obstacle_association obstacle_name="Eavesdrop access requests" ref_type="or" subobstacle_name="Eavesdrop request enforcement channel">
      <rationale></rationale>
    </obstacle_association>
    <obstacle_association obstacle_name="Eavesdrop access requests" ref_type="or" subobstacle_name="Eavesdrop Policy Manager">
      <rationale></rationale>
    </obstacle_association>
    <obstacle_association obstacle_name="Eavesdrop access requests" ref_type="or" subobstacle_name="Eavesdrop Context Manager">
      <rationale></rationale>
    </obstacle_association>
    <obstacle_association obstacle_name="Eavesdrop Context Manager" ref_type="or" subobstacle_name="Eavesdrop RPC Call Log">
      <rationale></rationale>
    </obstacle_association>
    <obstacle_association obstacle_name="Eavesdrop Context Manager" ref_type="or" subobstacle_name="Eavesdrop Context Database">
      <rationale></rationale>
    </obstacle_association>
  </implementation>
  <known_uses>None</known_uses>
  <related_patterns>None</related_patterns>
</attack_pattern>
