=== cairis-platform/cairis/dtd/synopses.dtd
<!-- 
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

<!-- DTD for characteristic, reference, and use case step synopses and contributions -->

<!ELEMENT synopses (characteristic_synopsis*,reference_synopsis*,step_synopsis*,reference_contribution*,usecase_contribution*)>
<!ELEMENT characteristic_synopsis EMPTY>
<!ATTLIST characteristic_synopsis characteristic CDATA #REQUIRED>
<!ATTLIST characteristic_synopsis synopsis CDATA #REQUIRED>
<!ATTLIST characteristic_synopsis dimension (goal | softgoal | task) #REQUIRED>
<!ATTLIST characteristic_synopsis actor_type (persona | asset | component) #REQUIRED>
<!ATTLIST characteristic_synopsis actor CDATA #REQUIRED>
<!ELEMENT reference_synopsis EMPTY>
<!ATTLIST reference_synopsis reference CDATA #REQUIRED>
<!ATTLIST reference_synopsis synopsis CDATA #REQUIRED>
<!ATTLIST reference_synopsis dimension (goal | softgoal | task) #REQUIRED>
<!ATTLIST reference_synopsis actor_type (persona | asset | component) #REQUIRED>
<!ATTLIST reference_synopsis actor CDATA #REQUIRED>
<!ELEMENT step_synopsis EMPTY>
<!ATTLIST step_synopsis usecase CDATA #REQUIRED>
<!ATTLIST step_synopsis environment CDATA #REQUIRED>
<!ATTLIST step_synopsis step_no CDATA #REQUIRED>
<!ATTLIST step_synopsis synopsis CDATA #REQUIRED>
<!ATTLIST step_synopsis actor_type (role | asset | component) #REQUIRED>
<!ATTLIST step_synopsis actor CDATA #REQUIRED>
<!ELEMENT reference_contribution EMPTY>
<!ATTLIST reference_contribution source CDATA #REQUIRED>
<!ATTLIST reference_contribution destination CDATA #REQUIRED>
<!ATTLIST reference_contribution means_end (means | end) #REQUIRED>
<!ATTLIST reference_contribution contribution (Make | SomePositive | Help | Hurt | SomeNegative | Break) #REQUIRED>
<!ELEMENT usecase_contribution EMPTY>
<!ATTLIST usecase_contribution usecase CDATA #REQUIRED>
<!ATTLIST usecase_contribution referent CDATA #REQUIRED>
<!ATTLIST usecase_contribution means_end (means | end) #REQUIRED>
<!ATTLIST usecase_contribution contribution (Make | SomePositive | Help | Hurt | SomeNegative | Break) #REQUIRED>

=== cairis-platform/cairis/cairis/test/persona_synopses.xml
<?xml version="1.0"?>
<!DOCTYPE synopses PUBLIC "-//CAIRIS//DTD SYNOPSES 1.0//EN" "https://cairis.org/dtd/synopses.dtd">

<synopses>
<!-- Justin characteristics -->
<characteristic_synopsis characteristic="Uses mobile applications frequently" synopsis="Mobile app reliance" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Hyperactive multi-tasker" synopsis="Multi-task activities" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Disposable income" synopsis="Purchase expensive tech" dimension="goal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Metrosexual" synopsis="Fashion conscious" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Exercises frequently" synopsis="Maintain healthy lifestyle" dimension="goal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Uses technology to organise life" synopsis="Technology-centricity" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Not particularly security or privacy conscious" synopsis="Maintain security indifference" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Willing to share personal data" synopsis="Share personal data" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Likes new gadgets and technology" synopsis="Uses new gadgets" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Cares deeply about style and personal appearance" synopsis="Maintain personal appearance" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Young and single" synopsis="Maintain independent life" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Enjoys using cutting-edge technology" synopsis="Apply cutting-edge tech" dimension="softgoal" actor_type="persona" actor="Justin" />
<characteristic_synopsis characteristic="Trusts technology" synopsis="Trust technology" dimension="softgoal" actor_type="persona" actor="Justin" />

<!-- Ethan characteristics -->
<characteristic_synopsis characteristic="Illegal spammer" synopsis="Send bulk email" dimension="goal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Student" synopsis="Study undergraduate degree" dimension="goal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Crime-prone" synopsis="Criminal tendancies" dimension="softgoal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Credit card data trader" synopsis="Trade credit card data" dimension="goal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Data harvester" synopsis="Harvest data" dimension="goal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Vulnerability exploiter" synopsis="Exploit vulnerabilities" dimension="softgoal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Hacktivist" synopsis="Promote online activism" dimension="softgoal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Wants to make money fast" synopsis="Make quick profit" dimension="softgoal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Botnet administrator knowledge" synopsis="Administer botnets" dimension="goal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Administration knowledge of spamming software" synopsis="Manage spamming infrastructure" dimension="goal" actor_type="persona" actor="Ethan" />
<characteristic_synopsis characteristic="Security aware" synopsis="Security perception" dimension="softgoal" actor_type="persona" actor="Ethan" />


<!-- Jimmy characteristics -->
<characteristic_synopsis characteristic="Focused on mobile and Web development" synopsis="Develop mobile webapps" dimension="softgoal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Passionate and experienced professional software developer" synopsis="Programmer lifestyle" dimension="softgoal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Passionate and successful blogger" synopsis="Blog experiences" dimension="goal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Knows what he wants and chooses tool chain and architectural design accordingly" synopsis="Select development toolchain" dimension="goal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Prefers open source" synopsis="Prefer open source" dimension="goal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Follows a pragmatic hands-on design and implementation approach" synopsis="Design pragmatically" dimension="softgoal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Knows how to do business with his applications" synopsis="Grow business" dimension="softgoal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Stays up-to-date on various technologies" synopsis="Maintain ecosystem awareness" dimension="softgoal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Is fond of gadgets which interact on his home network" synopsis="Hacker" dimension="softgoal" actor_type="persona" actor="Jimmy" />
<characteristic_synopsis characteristic="Is comfortable with developing low-level functional details" synopsis="Exploit device features" dimension="goal" actor_type="persona" actor="Jimmy" /> 

<!-- David characteristics -->

<characteristic_synopsis characteristic="Convicted felon" synopsis="Ex-prisoner" dimension="softgoal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="He is a talented sportsman" synopsis="Competitive sportsman" dimension="softgoal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="He is an expert car repairman" synopsis="Repair vehicles" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Frail personality" synopsis="" dimension="goal" actor_type="persona" actor="David" />

<!--<characteristic_synopsis characteristic="Hard life in early age" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Illegal inclination" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Uncomfortable to rules and laws" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Reckless" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Competitive" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Attention seeker" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Good problem solver" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Comfortable with car's internals" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Money greedy" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Knowledge of basic exploits" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Successful tamperer" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Deranged personality" synopsis="" dimension="goal" actor_type="persona" actor="David" />
<characteristic_synopsis characteristic="Careless of his own action's consequences" synopsis="" dimension="goal" actor_type="persona" actor="David" /> -->

<!-- Helen characteristics -->
<characteristic_synopsis characteristic="A Sales and Marketing manager" synopsis="Market products" dimension="goal" actor_type="persona" actor="Helen" />
<characteristic_synopsis characteristic="A professional commuter" synopsis="Commute to work" dimension="goal" actor_type="persona" actor="Helen" />
<characteristic_synopsis characteristic="Patterns of behaviour planned" synopsis="Plan schedule" dimension="goal" actor_type="persona" actor="Helen" />
<characteristic_synopsis characteristic="Is Family-centered" synopsis="Center life around family" dimension="softgoal" actor_type="persona" actor="Helen" />
<characteristic_synopsis characteristic="Maintains a Work-Life split" synopsis="Balance work and life" dimension="softgoal" actor_type="persona" actor="Helen" />
<characteristic_synopsis characteristic="Keeps busy" synopsis="Keep active" dimension="softgoal" actor_type="persona" actor="Helen" />
<characteristic_synopsis characteristic="Shares data to manage schedule" synopsis="Share work data" dimension="goal" actor_type="persona" actor="Helen" />


<!-- Helen references -->
<reference_synopsis reference="LinkedIn user" synopsis="Professionally social network" dimension="softgoal" actor_type="persona" actor="Helen" />
<reference_synopsis reference="Works office hours" synopsis="Work 9-5" dimension="softgoal" actor_type="persona" actor="Helen" />
<reference_synopsis reference="Receives LinkedIn notifications" synopsis="Track social network" dimension="goal" actor_type="persona" actor="Helen" />
<reference_synopsis reference="Car owner" synopsis="Possess vehicle" dimension="goal" actor_type="persona" actor="Helen" />
<reference_synopsis reference="SatNav driver" synopsis="Follow SatNav" dimension="goal" actor_type="persona" actor="Helen" />
